import Header from "@/components/landingpagecomponents/header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kargakarga",
  description: "Generated by Emre Ates",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta
        http-equiv="Content-Security-Policy"
        content="upgrade-insecure-requests"
      />
      <body className={inter.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
